In [1]:
import pandas as pd
import os
import numpy as np

In [2]:


data_path = "../data"

customers = pd.read_csv(f"{data_path}/customers.csv")
products = pd.read_csv(f"{data_path}/products.csv")
orders = pd.read_csv(f"{data_path}/orders.csv")
order_items = pd.read_csv(f"{data_path}/order_items.csv")
payments = pd.read_csv(f"{data_path}/payments.csv")
returns = pd.read_csv(f"{data_path}/returns.csv")
shipping = pd.read_csv(f"{data_path}/shipping.csv")
discounts = pd.read_csv(f"{data_path}/discounts.csv")
regions = pd.read_csv(f"{data_path}/regions.csv")

In [3]:
datasets = {
    "customers": customers,
    "products": products,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "returns": returns,
    "shipping": shipping,
    "discounts": discounts,
    "regions": regions
}

for name, df in datasets.items():
    print(name, df.shape)

customers (50000, 7)
products (1000, 7)
orders (100000, 6)
order_items (174849, 7)
payments (100000, 6)
returns (8900, 5)
shipping (100000, 8)
discounts (100, 6)
regions (16, 4)

In [4]:
datasets["customers"]["age_group"].sample(5)

35055    25-34
16497    18-24
39117    18-24
11648    25-34
43658    25-34
Name: age_group, dtype: object

In [5]:
datasets["customers"].sample(3)

,customer_id,signup_date,region_id,customer_segment,acquisition_channel,age_group,loyalty_tier
4871,C004872,2025-07-28,R12,Consumer,Organic,55+,Platinum
16509,C016510,2025-02-16,R08,Consumer,Organic,25-34,Bronze
37929,C037930,2024-10-17,R14,Consumer,Marketplace,45-54,Bronze

In [6]:
datasets["customers"].dtypes

customer_id            object
signup_date            object
region_id              object
customer_segment       object
acquisition_channel    object
age_group              object
loyalty_tier           object
dtype: object

In [7]:
datasets["customers"]["signup_date"] = pd.to_datetime(datasets["customers"]["signup_date"],errors = "coerce")

In [8]:
datasets["customers"]["age_min"] = (datasets["customers"]["age_group"].str.extract(r"(\d+)", expand=False).astype("Int64").fillna(0))

In [9]:
datasets["customers"]["age_max"] = (datasets["customers"]["age_group"].str.extract(r"-(\d+)",expand = False).astype("Int64").fillna(100))

In [10]:
datasets["customers"].sample(3)

,customer_id,signup_date,region_id,customer_segment,acquisition_channel,age_group,loyalty_tier,age_min,age_max
25394,C025395,2024-07-19,R10,Consumer,Social,25-34,Platinum,25,34
4255,C004256,2024-07-15,R04,Consumer,Paid Search,35-44,Bronze,35,44
42562,C042563,2024-04-30,R02,Consumer,Paid Search,35-44,Platinum,35,44

In [11]:
datasets["products"].sample(3)

,product_id,category,subcategory,brand,unit_cost,list_price,supplier_id
963,P00964,Books,Children,Brand_100,4632.03,6440.36,S018
121,P00122,Home & Kitchen,Cookware,Brand_116,3727.41,6268.18,S061
589,P00590,Sports,Cycling,Brand_099,6304.34,9573.83,S059

In [12]:
datasets["products"].dtypes

product_id      object
category        object
subcategory     object
brand           object
unit_cost      float64
list_price     float64
supplier_id     object
dtype: object

In [13]:
datasets["orders"].sample(3)

,order_id,customer_id,order_date,channel,order_status,payment_method
99367,O0099368,C016528,2025-12-16,Website,Delivered,UPI
18412,O0018413,C025488,2024-12-05,Website,Delivered,COD
77527,O0077528,C021228,2025-09-21,Marketplace,Pending,UPI

In [14]:
datasets["orders"].dtypes

order_id          object
customer_id       object
order_date        object
channel           object
order_status      object
payment_method    object
dtype: object

In [15]:
datasets["orders"]["order_date"] = pd.to_datetime(datasets["orders"]["order_date"],errors = "coerce")

In [16]:
datasets["order_items"].sample(3)

,order_id,product_id,quantity,unit_price,discount_pct,net_sales,estimated_cost
19066,O0010873,P00620,1,7772.92,14.45,6649.73,6797.07
127653,O0073141,P00498,1,21673.51,4.80,20633.18,13330.73
4236,O0002430,P00564,1,4445.88,12.29,3899.48,3927.17

In [17]:
datasets["order_items"].dtypes

order_id           object
product_id         object
quantity            int64
unit_price        float64
discount_pct      float64
net_sales         float64
estimated_cost    float64
dtype: object

In [18]:
datasets["payments"].sample(3)

,order_id,order_date,payment_method,payment_id,payment_status,transaction_amount
82307,O0082308,2024-04-12,Wallet,PAY0082308,Success,14688.21
88295,O0088296,2025-10-19,UPI,PAY0088296,Success,3855.79
15406,O0015407,2025-01-02,Credit Card,PAY0015407,Success,1899.05

In [19]:
datasets["payments"].dtypes

order_id               object
order_date             object
payment_method         object
payment_id             object
payment_status         object
transaction_amount    float64
dtype: object

In [20]:
datasets["payments"]["order_date"] = pd.to_datetime(datasets["payments"]["order_date"],errors = "coerce")

In [21]:
datasets["returns"].sample(3)

      return_id  order_id return_date  return_reason  refund_amount
2691  RET002692  O0030668  2025-05-08  Quality Issue        8373.56
7583  RET007584  O0085565  2024-09-10   Changed Mind       11062.16
6552  RET006553  O0073687  2024-05-17  Quality Issue       18009.89

In [22]:
datasets["returns"].dtypes

return_id         object
order_id          object
return_date       object
return_reason     object
refund_amount    float64
dtype: object

In [23]:
datasets["returns"]["return_date"] = pd.to_datetime(datasets["returns"]["return_date"],errors = "coerce")

In [24]:
datasets["shipping"].sample(3)

,order_id,order_date,shipping_id,promised_delivery_date,actual_delivery_date,shipping_cost,carrier,delivery_status
29455,O0029456,2025-04-04,SHP0029456,2025-04-10,2025-04-11,48.62,EcomExpress,Delayed
85697,O0085698,2025-06-23,SHP0085698,2025-06-26,2025-06-29,128.79,DTDC,Delayed
84011,O0084012,2025-12-27,SHP0084012,2025-12-29,2026-01-08,278.93,EcomExpress,Delayed

In [25]:
datasets["shipping"].dtypes

order_id                   object
order_date                 object
shipping_id                object
promised_delivery_date     object
actual_delivery_date       object
shipping_cost             float64
carrier                    object
delivery_status            object
dtype: object

In [26]:
col = ["order_date","promised_delivery_date","actual_delivery_date"]
for i in col:
 datasets["shipping"][i] = pd.to_datetime(datasets["shipping"][i], errors = "coerce")

In [27]:
datasets["discounts"].sample(3)

,discount_id,campaign_name,discount_type,planned_discount_pct,campaign_start,campaign_end
73,D0074,Campaign_074,Flash Sale,23.76,2024-07-23,2024-09-02
43,D0044,Campaign_044,Loyalty,5.95,2024-12-07,2025-01-03
80,D0081,Campaign_081,Flash Sale,28.28,2024-09-14,2024-10-20

In [28]:
datasets["discounts"].dtypes

discount_id              object
campaign_name            object
discount_type            object
planned_discount_pct    float64
campaign_start           object
campaign_end             object
dtype: object

In [29]:
datasets["discounts"]["campaign_start"] = pd.to_datetime(datasets["discounts"]["campaign_start"], errors = "coerce")
datasets["discounts"]["campaign_end"] = pd.to_datetime(datasets["discounts"]["campaign_end"], errors = "coerce")

In [30]:
datasets["regions"].sample(3)

   region_id        city       state   zone
11       R12  Chandigarh  Chandigarh  North
14       R15       Patna       Bihar   East
4        R05   Bengaluru   Karnataka  South

In [31]:
datasets["regions"].dtypes

region_id    object
city         object
state        object
zone         object
dtype: object

In [32]:
for name , df in datasets.items():
    missing = df.isna().sum()
    
    print(missing)

customer_id              0
signup_date              0
region_id                0
customer_segment         0
acquisition_channel      0
age_group              500
loyalty_tier             0
age_min                  0
age_max                  0
dtype: int64
product_id     0
category       0
subcategory    0
brand          0
unit_cost      0
list_price     0
supplier_id    0
dtype: int64
order_id            0
customer_id         0
order_date          0
channel           800
order_status        0
payment_method      0
dtype: int64
order_id             0
product_id           0
quantity             0
unit_price           0
discount_pct      1200
net_sales            0
estimated_cost       0
dtype: int64
order_id              0
order_date            0
payment_method        0
payment_id            0
payment_status        0
transaction_amount    0
dtype: int64
return_id        0
order_id         0
return_date      0
return_reason    0
refund_amount    0
dtype: int64
order_id                    0
order_date                  0
shipping_id                 0
promised_delivery_date      0
actual_delivery_date        0
shipping_cost               0
carrier                   400
delivery_status             0
dtype: int64
discount_id             0
campaign_name           0
discount_type           0
planned_discount_pct    0
campaign_start          0
campaign_end            0
dtype: int64
region_id    0
city         0
state        0
zone         0
dtype: int64

In [33]:
datasets["customers"] = datasets["customers"].drop(columns = "age_group")

In [34]:
datasets["orders"]["channel"] = datasets["orders"]["channel"].fillna(datasets["orders"]["channel"].mode()[0])

In [35]:
datasets["order_items"].sample(3)

,order_id,product_id,quantity,unit_price,discount_pct,net_sales,estimated_cost
159965,O0091584,P00449,1,4308.15,11.79,3800.22,2643.97
90293,O0051705,P00849,1,17387.58,NaN,15867.91,14348.84
6342,O0003615,P00588,1,21140.83,0.95,20939.99,14212.07

In [36]:
datasets["order_items"]["discount_pct"] = datasets["order_items"]["discount_pct"].fillna(datasets["order_items"]["discount_pct"].mean())

In [37]:
datasets["order_items"]["gross_profit"] = (
    datasets["order_items"]["net_sales"]
    - datasets["order_items"]["estimated_cost"]
)

In [64]:
datasets["order_items"]["gross_profit"].sample(4)

29712     735.07
46951    4305.04
74767    9872.63
2310     1612.44
Name: gross_profit, dtype: float64

In [61]:
datasets["order_items"]["profit_margin_pct"] = np.where(order_items["net_sales"] > 0,
    datasets["order_items"]["gross_profit"]
    / datasets["order_items"]["net_sales"] * 100,
    np.nan
)

In [59]:
datasets["order_items"]["profit_margin_pct"].sample(4)

174307    36.583659
170886    15.878083
52393      1.492586
96645     22.837292
Name: profit_margin_pct, dtype: float64

In [40]:
order_metrics = (
    datasets["order_items"]
    .groupby("order_id")
    .agg(
        gross_sales=("unit_price", lambda x: 0),
        net_sales=("net_sales", "sum"),
        estimated_cost=("estimated_cost", "sum"),
        gross_profit=("gross_profit", "sum")
    )
    .reset_index()
)

In [56]:
order_metrics.sample(4)

,order_id,gross_sales,net_sales,estimated_cost,gross_profit,profit_margin_pct
64750,O0064751,21543.56,18550.29,14568.41,3981.88,21.465325
53707,O0053708,21073.69,19815.35,14542.14,5273.21,26.611743
97333,O0097334,15488.90,14602.93,14083.35,519.58,3.558053
9948,O0009949,5876.86,5286.82,4051.27,1235.55,23.370381

In [41]:
datasets["order_items"]["gross_sales"] = (datasets["order_items"]["quantity"]* datasets["order_items"]["unit_price"])

In [42]:
order_metrics = (
    datasets["order_items"]
    .groupby("order_id")
    .agg(
        gross_sales=("gross_sales", "sum"),
        net_sales=("net_sales", "sum"),
        estimated_cost=("estimated_cost", "sum"),
        gross_profit=("gross_profit", "sum")
    )
    .reset_index()
)

In [43]:
order_metrics["profit_margin_pct"] = np.where(
    order_metrics["net_sales"] > 0,
    order_metrics["gross_profit"]
    / order_metrics["net_sales"] * 100,
    np.nan
)

In [44]:
orders = orders.merge(
    order_metrics,
    on="order_id",
    how="left"
)

In [45]:
datasets["shipping"].sample(3)

,order_id,order_date,shipping_id,promised_delivery_date,actual_delivery_date,shipping_cost,carrier,delivery_status
47949,O0047950,2024-02-12,SHP0047950,2024-02-16,2024-02-16,58.13,DTDC,On Time
90159,O0090160,2025-05-25,SHP0090160,2025-05-30,2025-06-01,256.12,Delhivery,Delayed
7270,O0007271,2025-02-10,SHP0007271,2025-02-13,2025-02-15,209.01,DTDC,Delayed

In [46]:
datasets["shipping"]["carrier"] = datasets["shipping"]["carrier"].fillna("Unknown")

In [47]:
datasets["shipping"]["delivery_delay_days"] = (
    datasets["shipping"]["actual_delivery_date"]
    - datasets["shipping"]["promised_delivery_date"]
).dt.days

In [65]:
datasets["shipping"]["delivery_delay_days"].sample(4)

6406     2
42528    0
33950    0
80766    2
Name: delivery_delay_days, dtype: int64

In [48]:
datasets["shipping"]["delivery_delay_days"] = (
    datasets["shipping"]["delivery_delay_days"]
    .clip(lower=0)
)

In [49]:
for name , df in datasets.items():
    missing = df.isna().sum()
    
    print(missing)

customer_id            0
signup_date            0
region_id              0
customer_segment       0
acquisition_channel    0
loyalty_tier           0
age_min                0
age_max                0
dtype: int64
product_id     0
category       0
subcategory    0
brand          0
unit_cost      0
list_price     0
supplier_id    0
dtype: int64
order_id          0
customer_id       0
order_date        0
channel           0
order_status      0
payment_method    0
dtype: int64
order_id             0
product_id           0
quantity             0
unit_price           0
discount_pct         0
net_sales            0
estimated_cost       0
gross_profit         0
profit_margin_pct    0
gross_sales          0
dtype: int64
order_id              0
order_date            0
payment_method        0
payment_id            0
payment_status        0
transaction_amount    0
dtype: int64
return_id        0
order_id         0
return_date      0
return_reason    0
refund_amount    0
dtype: int64
order_id                  0
order_date                0
shipping_id               0
promised_delivery_date    0
actual_delivery_date      0
shipping_cost             0
carrier                   0
delivery_status           0
delivery_delay_days       0
dtype: int64
discount_id             0
campaign_name           0
discount_type           0
planned_discount_pct    0
campaign_start          0
campaign_end            0
dtype: int64
region_id    0
city         0
state        0
zone         0
dtype: int64

In [50]:
for name, df in datasets.items():

    print(
        name,
        "duplicate rows:",
        df.duplicated().sum()
    )

customers duplicate rows: 0
products duplicate rows: 0
orders duplicate rows: 0
order_items duplicate rows: 0
payments duplicate rows: 0
returns duplicate rows: 0
shipping duplicate rows: 0
discounts duplicate rows: 0
regions duplicate rows: 0

In [51]:
quality_report = []

for name, df in datasets.items():

    quality_report.append({
        "table": name,
        "rows": len(df),
        "columns": len(df.columns),
        "missing_cells": df.isnull().sum().sum(),
        "duplicate_rows": df.duplicated().sum()
    })

quality_report = pd.DataFrame(quality_report)

quality_report

         table    rows  columns  missing_cells  duplicate_rows
0    customers   50000        8              0               0
1     products    1000        7              0               0
2       orders  100000        6              0               0
3  order_items  174849       10              0               0
4     payments  100000        6              0               0
5      returns    8900        5              0               0
6     shipping  100000        9              0               0
7    discounts     100        6              0               0
8      regions      16        4              0               0

In [52]:
CLEAN_PATH = "../data/cleaned"

import os
os.makedirs(CLEAN_PATH, exist_ok=True)

In [53]:
for name, df in datasets.items():
    df.to_csv(
        f"{CLEAN_PATH}/{name}.csv",
        index=False
    )